project_name: predator

before:
  hooks:
    - make install
builds:
  - main: ./main.go
    id: "predator"
    binary: predator
    flags:
      - -a
    ldflags:
      - -s -w -X github.com/goto/predator/conf.BuildVersion={{.Tag}} -X github.com/goto/predator/conf.BuildCommit={{.FullCommit}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: macos
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  draft: true
  prerelease: auto
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^build'
      - '^chore'
dockers:
  -
    goos: linux
    goarch: amd64
    ids:
      - predator
    dockerfile: Dockerfile
    image_templates:
      - 'docker.io/gotocompany/{{.ProjectName}}:{{ .Version }}'
      - 'docker.io/gotocompany/{{.ProjectName}}:{{ .Version }}-amd64'
